CREATE TABLE users(
    user_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE company(
    company_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
     email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);


